#name: qr2
channels:
  - defaults
  - python
  - conda-forge
dependencies:
  - pyqt
  - pip
  - python #>=3.8
  - setuptools
  - sqlite
  - tk
  - numpy
  - pytorch-gpu
  - scikit-learn
  - cython
  - matplotlib
  - torchvision
  - zbar
  - pip:
    - qrcode
    - opencv-python==4.3.0.36
    - requests
    - pillow-simd>=5.0.0 # PILLOW_VERSION => __version__
    - scikit-image
    - editdistance
    - easydict
    - torchsummary
    - pyzbar



# prefix: /home/taylor/env/anaconda3/envs/qr
# conda env update -f environment.yaml
# pip install qrcode[pil]
# conda env create -f environment.yaml --prefix /zgrouphome/fslg_qr/env/qr